logging:
  level: INFO
  file_name: 'app.log'
  format: '%(asctime)s - %(levelname)s - %(filename)s - Line %(lineno)d - %(message)s'
data:
  data_dir: '../customerchurn_prediction_mlops_project/data'
  raw_filename : 'Customer-Churn-Records.csv'
  train_test_filename: 'train_cv_test_data_raw.csv'
  unit_integration_filename : 'unit_integration_test_data_raw.csv'
  batch_test_filename: 'batch_test_data_raw.csv'
  encoder_dir: 'encoder'
  eda_dir: 'eda_output'
  cat_eda_file : 'cat_eda.png'
  num_eda_file : 'num_eda.png'
  corr_eda_file : 'corr_eda.png'
  training_data_filename : 'training_data_processed.csv'
  validation_data_filename : 'validation_data_processed.csv'
  testing_data_filename : 'testing_data_processed.csv'
  unit_integration_processed_filename: 'unit_integration_test_data_processed.csv'
  unit_integration_predicted_filename: 'unit_integration_test_data_predicted.csv'
  batch_test_processed_filename: 'batch_test_data_processed.csv'
  batch_test_predicted_filename: 'batch_test_data_predicted.csv'
  index_col:
    - 'RowNumber'
  cols_to_drop:
    - 'CustomerId'
    - 'Surname'
  cat_columns:
    - 'Gender'
    - 'Geography'
    - 'Card Type'
    - 'Tenure'
    - 'NumOfProducts'
    - 'Satisfaction Score'
  numerical_columns:
    - 'CreditScore'
    - 'Age'
    - 'Balance'
    - 'EstimatedSalary'
    - 'Point Earned'
  cat_columns_to_encode:
    - 'Gender'
    - 'Geography'
    - 'Card Type'
    - 'Tenure'
    - 'NumOfProducts'
    - 'Satisfaction Score'
  target_column:
    - 'Exited'
models:
  model_artifact_dir: '../customerchurn_prediction_mlops_project/model_artifacts'
  baseline_model:
    experiment_name: 'LR_Tuning'
    cm_filename: 'lr_confusionmatrix.png'
  random_forest:
    model_parameters:
      param_grid:
        n_estimators: [50, 100, 200, 300]
        max_depth: [5, 7, 10]
        min_samples_split: [2, 5, 10]
      class_weight: 'balanced'
    experiment_name: 'RF_Tuning'
    model_filename: 'rf_model.joblib'
    params_filename: 'rf_params.joblib'
    cm_filename: 'rf_confusionmatrix.png'
  gradient_boosting:
    model_parameters:
      param_grid:
        n_estimators: [50, 100, 150]
        learning_rate: [0.1, 0.01]
        max_depth: [3, 5, 7]
    experiment_name: 'GB_Tuning'
    model_filename: 'gb_model.joblib'
    params_filename: 'gb_params.joblib'
    cm_filename: 'gb_confusionmatrix.png'
mlflow:
  tracking_uri: 'sqlite:///mlflow.db'
  experiment_name: 'customer_churn_prediction'
  best_artifact_experiment_name: 'customer_churn_prediction'


