name: MLOps Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mlops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
    
      - name: Start MLflow server
        run: |
          mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlflow-artifacts --host 0.0.0.0 &

      - name: Check if Prefect Server is Running
        run: |
          if pgrep -x "prefect" > /dev/null; then
            echo "Stopping Prefect Server..."
            prefect server stop
          fi

      - name: Start Prefect Server
        run: |
          nohup prefect server start > prefect_server_logs.txt 2>&1 &
          
      - name: Prefect Cloud Login
        run: |
          prefect cloud login -k ${{ secrets.PREFECT_API_KEY }} --workspace MyWorkspace
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}

      - name: Run model training
        run: python training_flow.py  # Modify this based on your project structure
        
      - name: Test model and deploy in docker
        run: python src/runtest_deploy.py  # Modify this based on your project structure
